### PR TITLE
Package AppJS into Mac OSX Application Bundle. (Plus a documentation fix.)

### PR DESCRIPTION
**Pull request by DanBUK**
Template files for .app bundling on MacOS with small package script to build the Hello World example into a App Bundle.

Added F11 to Hello World example to show Full Screen usage.

I made a typo for osx build environment setup.

### CODE REVIEW

**Comment by DanBUK** [comment]
I will update the example to not use F keys.

**Comment by graphnode** [comment]
Isn't F11 the usual key for fullscreen? Is this key reserved on Mac or Linux?

**Comment by DanBUK** [comment]
On Mac by default one would need to use Fn+F11 to achieve 'F11' keypress. I've noticed in my testing that capturing 'normal' keys cannot be achieved using window.addEventListener('keydown') as the context is going to be one of the HTML elements that has focus.

I may just remove the key binding from the example completely.

**Comment by ghost** [comment]
I forgot to push a solution for this I came up with last night. It's in Hello World now.

**Comment by ghost** [comment]
Also this is useful for playing with keybinds: http://benvie.github.com/Keyboard/

**Comment by DanBUK** [comment]
Going to re-submit pull requests _properly_..

**Pull request closed without merging**
