### PR TITLE
Memory Leaks in V8StringToChar and its invocations

### PR DESCRIPTION
**Pull request by ashishnegi**
Following on the issue https://github.com/appjs/appjs/issues/382 I have used:
1. std::unique_ptr instead of raw pointers.
2. Invocations of V8StringToChar has been changed to either get() or release(), depending upon what i thought was required at that position.

I first tried with shared_ptr but since we do not need many pointers to point to this memory we should use unique_ptr. Hence moved to it.

### CODE REVIEW

**Comment by milani** [comment]
Thank you:) Let me merge it manually and test on other platforms.

**Comment by ashishnegi** [comment]
That would be right way. If this would test right, i would also do it for the rest of other functions like V8StringToWchar .

**Comment by IngwiePhoenix** [comment]
Is this still current? If so, I'd merge it if possible - or needed. I belive @milani hasn't merged it yet.

**Comment by ashishnegi** [comment]
Yaa. he had talked about looking into it on local machine.

**Comment by IngwiePhoenix** [comment]
Altight, looks like thats my job now, as I own appjs now. Or more, i am the head maintainer. :) Let’s see how that’ll behave! ^^
Am 23.12.2013 um 13:00 schrieb ASHISH NEGI notifications@github.com:

**Comment by ashishnegi** [comment]
any progress on this Ingwie.

**Comment by ashishnegi** [comment]
Closing PR as no response for long time.

**Pull request closed without merging**
