### PR TITLE
application packaging

### PR DESCRIPTION
**Pull request by sihorton**
This patch adds application package handling to appjs. Also included are minor changes to the launch project for windows so that I could successfully build app.exe

The helloWorld application has had its app.js file updated to use the appjs-package npm module for handling package files. The aim has been to place the majority of changes and code into this module so that this change impacts the current functionality as little as possible, just adding in the additional ability to handle .appjs files that are passed to it.

http://appjs.delightfulsoftware.com/win.htm gives a screenshot tour of how it works on windows.

The application package contains a list of dependencies, these are scanned and any missing dependencies are downloaded from a url found in the package file. Once installed the application is then launched.

Please note that while this works with 0.0.19 running the same code in 0.0.20 does not open the application window. I am reading in the app.js file from the package and evaluating it, but for some reason in 20 on windows this does not work (it still works fine with a normal unpackaged application). Swapping the appjs and appjs-win32 folders (i.e. the node_modules) to 0.0.19 works so my guess is there is some small problem affecting the latest release.

This can be considered a work in progress and I am very open to suggestions and changes. This should work cross platform -- it is all javascript code, but I have not yet tested on linux or mac.

### CODE REVIEW

**Comment by sihorton** [comment]
I have done a lot of debugging on the 0.20 version and it seems to be some form of path issue. This should mean I can create a workaround.

**Comment by sihorton** [comment]
The problem was caused by reading the icons, since I have packaged the applications appjs cannot read the applications directly from the disk. I have created a workaround for now that reads the icons from the appjs install directory instead. I will cancel this pull request, re-apply my changes and submit again.

**Comment by milani** [comment]
C++ addon reads icons directly. Instead we should pass it a buffer of icon file content. This way we can read the icon from package in js side, pass the buffer to C++. I don't know if it is possible or not.

**Comment by sihorton** [comment]
We could also just extract the icons to a temporary folder and read them from there for now. Buffer would be a better long term solution though. I use a router so ideally appjs could make a "request" for the file and use the result of that to pass icon to C++.

**Comment by milani** [comment]
We don't know which file is an icon and which is not. There are icons for menu, window etc. all need special care. They don't use router, actually they can not. For example in Win32, to create an icon for a menu item, I pass file path to GDI method `Gdiplus::Bitmap::FromFile` and it returns a handle to Bitmap icon! We should find methods to create Bitmap icon from file content instead.

**Comment by sihorton** [comment]
I understand. We could have a directory called "icons" or similar in the package, then the appjs-package module can detect those files and extract them or ideally read them into memory and make the main appjs package aware of the resources something like app.addResource(name, Stream)  and then behind the scenes the module can do what is needed for the various platforms. It is probably going to be a bit messy to get it working well, but we can use workarounds for now.

**Comment by sihorton** [comment]
I have implemented a fix for this problem. The app.js code should call a method app.prepareIcons(['content/icons/32.png'],function(err, iconList) {
     var statusIcon = app.createStatusIcon({
          icon:iconList['content/icons/32.png'],
          tooltip:'AppJS Hello World',
          menu:trayMenu
        });

});
iconList is a hashmap that returns the full path to a file so you can pass that into the c++ code. Internally when running packages appjs extracts the icons to a cache directory and uses a sha1 to name the file (to avoid duplicates). So when running inside a package file you would have to explicitly call the prepareIcons function. We can just add that function call to all of the examples on the website and the documentation and it should not cause any problems.

**Pull request closed without merging**
