### PR TITLE
Router Upgrade

### PR DESCRIPTION
**Pull request by Takeno**
Hi!

I rewrote the router of appjs using some methods of ExpressJs router lib, merging them with your code.
The new features are:
- Wildcard/Params in url request (like: '/user/:id' => req.params.id)
- method res.sendFile() to send static file not only in GET requests
- new app.use() method to add "extensions" that may manipulate req/res before "view" callback

I propose also a new order for middleware executions:
- 1^ Global Handlers => function(req, res, next) which is run every request
- 2^ Method Handlers => function(req, res, next) which is run only in specified method request
- 3^ Route Handler => the last function(req, res) which is run only if route match the pathname

PS: I found this lib: http://tempojs.com/ . Can be useful integrate it in appjs?

This is my first pull request, so be careful for my possible errors.
I hope this can help the project.

... and sorry for my terrible english! :(

### CODE REVIEW

**Comment by milani** [comment]
Hey!

Thank you for your nice work. Before merging we need to discuss somethings.
- npm-debug.log is committed to the project. We don't want it.
- You added global router settings (caseSensitive and the other option) to window settings. This is not logical. window settings are specific to an instance of window. But router settings are application-wide settings. So we should separate them.
- Do we really need these settings?

I didn't traced the whole patch, I add more comments later. It seems you added very nice features I was thinking about like url parameters. Before making any further change, please discuss it first in appjs-dev mailing list so we can decide what is the best thing to put our effort on:) 

Thank you again for the pull request. I know you have spent a lot of your valuable time on it.

**Comment by Takeno** [comment]
You're right! I will subscribe the appjs-dev mailing list soon.

For these settings, maybe we don't need them. I'm only a WebDev (no desktop) so I was thinking about router like my habit, for web server! Instead man who compose url request is the same of who build the software.

We will discuss the others issues in mailing list.

**Comment by michael-lawrence** [comment]
Would there possibly be a way to just use express as pluggable routing library? Would be great if the routing was abstracted out so we could use custom routing libraries if needed.

**Comment by milani** [comment]
@michael-lawrence Request and Response objects that we use are not http compatible so routing libraries can not handle them. I try to figure out how it can be made possible.

@Takeno We are changing the appjs API which is time consuming and during that we changed routers a lot so I will merge your changes manually after refactoring AppJS. Thank you for your nice work.

**Comment by Takeno** [comment]
@milani Are you sure? I can clone this new appjs, write again the router and re-open a pull request; in this way you can work on other features. I wrote in the mailing-list "Router Upgrade" topic some days ago, if we want discuss what features of my pull request we need.

**Pull request closed without merging**
